// Generated by Copilot, modified...
import type { DTickValue, Layout } from 'plotly.js-dist-min';
import type { FoldType } from '@/esri/services/aggregation';


// Main style configuration for each fold type
type PredefinedFoldTypes = Exclude<FoldType,
  | 'noneOfDay'
  | 'noneOfWeek'
  | 'noneOfMonth'
  | 'noneOfYear'
>;

const plotlyGridStyles = {
  'xaxis': {
    'showgrid': true,
    // 'gridcolor': 'red',
    // 'gridwidth': 1,
    // 'zerolinecolor': 'blue',
    // 'zerolinewidth': 2,
  }
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function num2TimeLabel(hour: number): string {
  const h = Math.floor(hour % 24);
  const ampm = h >= 12 ? 'PM' : 'AM';
  const hour12 = h % 12 === 0 ? 12 : (h % 12); // just get hour diget
  
  const minute = Math.round((hour % 1) * 60);
  
  if (minute === 0) {
    return `${hour12.toFixed(0)} ${ampm}`;
  }
  if (minute == 60) {
    return `${(hour12 + 1).toFixed(0)} ${ampm}`;
  }
  
  return `${hour12.toFixed(0)}:${minute.toFixed(0).padStart(2, '0')} ${ampm}`;
}
// create an object like 0: 12 AM, 0.1: 12:06 AM, 0.2: 12:12 AM, ..., 23.9: 11:54 PM
const timeLabelAlias: Record<string, string> = {};
for (let h = 0; h < 24; h += 0.1) {
  h = Math.round(h * 10) / 10; // avoid floating point precision issues
  const hasDecimal = h % 1 !== 0;
  if (hasDecimal) {
    timeLabelAlias[h.toFixed(1)] = num2TimeLabel(h);
    continue;
  }
  timeLabelAlias[parseInt(h.toFixed(1))] = num2TimeLabel(h);
}

// create weekday/weekend label alias
// weekday is 0, 23, weekend 24-47
const weekdayWeekendAlias: Record<string, string> = {};
for (let h = 0; h < 48; h += 0.1) {
  const dayHour = h % 24;
  const isWeekend = h >= 24;
  let label = num2TimeLabel(dayHour) + (isWeekend ? ' (WE)' : ' (WD)');
  // between 20 - 28 label is none
  if (h >= 20 && h < 28) {
    label = '';
  }
  const key = Math.round(h * 10) / 10; // avoid floating point precision issues
  if (key % 1 !== 0) {
    weekdayWeekendAlias[key.toFixed(1)] = label;
  } else {
    weekdayWeekendAlias[parseInt(key.toFixed(1))] = label;
  }
}

const _defaultyAxisStyle: Partial<Layout> = {
  'yaxis': {
    'automargin': true,
  }
};

export const foldTypeStyles: Record<PredefinedFoldTypes, Partial<Layout>> = {
  // Hour-based bins
  'hourOfDay': {
    xaxis: {
      title: { text: 'Hour of Day (Local Time for Region)' },
      tickmode: 'auto',
      tick0: 0,
      nticks: 7,
      labelalias: timeLabelAlias as unknown as DTickValue
    }
  },
  
  'hourOfWeek': {
    xaxis: {
      title: { text: 'Day of Week' },
      tickmode: 'array',
      tickvals: [0, 24, 48, 72, 96, 120, 144].map(v => v + 12),
      ticktext: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      minor: {
        gridcolor: 'black',
        gridwidth: 1,
        showgrid: true,
        tickmode: 'array',
        tickvals: [0, 24, 48, 72, 96, 120, 144],
        ticklen: 0,
      }
    },
  },
  
  'hourOfMonth': {
    xaxis: {
      title: { text: 'Hour of Month' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 24 * 5, // Every 5 days
      tickformat: 'd'
    }
  },
  
  'hourOfYear': {
    xaxis: {
      title: { text: 'Day of Year' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 24 * 30, // Roughly monthly
      tickformat: 'd',
    }
  },
  
  'hourOfSeason': {
    xaxis: {
      title: { text: 'Hour of Season' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 24 * 7, // Weekly
      tickformat: 'd'
    }
  },
  
  // Day-based bins
  'dayOfWeek': {
    xaxis: {
      title: { text: 'Day of Week' },
      tickmode: 'array',
      tickvals: [0, 1, 2, 3, 4, 5, 6].map(v => v + 0.5),
      ticktext: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      minor: {
        gridcolor: 'black',
        gridwidth: 1,
        showgrid: true,
        tickmode: 'array',
        tickvals: [0, 1, 2, 3, 4, 5, 6],
        ticklen: 0,
      }
    }
  },
  
  'dayOfMonth': {
    xaxis: {
      title: { text: 'Day of Month' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 5,
      tickformat: 'd'
    }
  },
  
  'dayOfYear': {
    xaxis: {
      title: { text: 'Day of Year' },
      tickmode: 'array',
      tickvals: [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334],
      ticktext: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    }
  },
  
  'dayOfSeason': {
    xaxis: {
      title: { text: 'Day of Season' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 10,
      tickformat: 'd'
    }
  },
  
  // Week-based bins
  'weekOfMonth': {
    xaxis: {
      title: { text: 'Week of Month' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 1,
      tickformat: 'd'
    }
  },
  
  'weekOfYear': {
    xaxis: {
      title: { text: 'Week of Year' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 4,
      tickformat: 'd'
    }
  },
  
  'weekOfSeason': {
    xaxis: {
      title: { text: 'Week of Season' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 2,
      tickformat: 'd'
    }
  },
  
  // Month-based bins
  'monthOfYear': {
    xaxis: {
      title: { text: 'Month of Year' },
      tickmode: 'array',
      tickvals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      ticktext: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    }
  },
  
  'monthOfSeason': {
    xaxis: {
      title: { text: 'Month of Season' },
      tickmode: 'array',
      tickvals: [0, 1, 2],
      ticktext: ['Month 1', 'Month 2', 'Month 3']
    }
  },
  
  // None-period bins (simple binning with dates)
  'noneOfNone': {
    xaxis: {
      title: { text: 'Date' },
      type: 'date',
      // tickformat: '%Y-%m-%d'
    }
  },
  
  'hourOfNone': {
    xaxis: {
      title: { text: 'Date' },
      type: 'date',
      // tickformat: '%Y-%m-%d %H:%M'
    }
  },
  
  'dayOfNone': {
    xaxis: {
      title: { text: 'Date' },
      type: 'date',
      // tickformat: '%Y-%m-%d'
    }
  },
  
  'weekOfNone': {
    xaxis: {
      title: { text: 'Date' },
      type: 'date',
      // tickformat: '%Y-%m-%d'
    }
  },
  
  'monthOfNone': {
    xaxis: {
      title: { text: 'Date' },
      type: 'date',
      // tickformat: '%Y-%m'
    }
  },
  
  // Special cases
  'dayOfWeekdayWeekend': {
    xaxis: {
      title: { text: 'Day Type' },
      tickmode: 'array',
      tickvals: [0, 1],
      ticktext: ['Weekday', 'Weekend'],
      range: [-0.5, 1.5],
    }
  },
  
  'hourOfWeekdayWeekend': {
    xaxis: {
      title: { text: 'Hour of Day' },
      tickmode: 'linear',
      tick0: 0,
      dtick: 3,
      // tickvals: [0, 6, 12, 18, 24, 30, 36, 42],
      // ticktext: ['0:00 WD', '6:00 WD', '12:00 WD', '18:00 WD', '0:00 WE', '6:00 WE', '12:00 WE', '18:00 WE']
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      labelalias: weekdayWeekendAlias as unknown as any
      // tickvals: [12, 36],
      // ticktext: ['Weekday', 'Weekend'],
      // minor: {
      //   showgrid: false,
      //   tickmode: 'linear',
      //   tick0: 0,
      //   dtick: 1,
      //   ticklen: 5,
      //   ticks: 'inside',
      // }
      
    }
  }
};

/**
 * Get the Plotly layout styling for a specific fold type
 */
export function getFoldTypeStyle(foldType: FoldType): Partial<Layout> {
  if (foldType.startsWith('none')) {
    return foldTypeStyles[foldType.replace('noneOf', 'hourOf') as PredefinedFoldTypes];
  }
    
  return foldTypeStyles[foldType];
}

export function deepMerge(base: object, updates: object): object {
  const result = {...base};
  for (const key in updates) {
    // if key has a non-array object, iterate recursively
    if (updates[key] && typeof updates[key] === 'object' && !Array.isArray(updates[key])) {
      result[key] = deepMerge(result[key] || {}, updates[key]);
    } else {
      result[key] = updates[key];
    }
  }
  return result;
}


export function mergeFoldTypeLayout(foldType: FoldType, customLayout?: Partial<Layout>): Partial<Layout> {
  const foldStyle = deepMerge(getFoldTypeStyle(foldType), _defaultyAxisStyle);
  const layout = deepMerge(deepMerge(foldStyle, plotlyGridStyles) , customLayout || {});

  const xaxisTitle = layout["xaxis"]?.title?.text;
  if (xaxisTitle) {
    const prefix = "Time: ";
    if (!xaxisTitle.startsWith(prefix)) {
      layout["xaxis"].title.text = `${prefix}${xaxisTitle}`;
    }
  }

  return layout;
}


import { DEFAULT_PLOT_LAYOUT } from './defaults';

export function withPlotlyDefaults(layout: Partial<Layout>) {
  return deepMerge(DEFAULT_PLOT_LAYOUT, layout);
}