<!-- Generated by Copilot -->
<template>
  <v-card variant="outlined" class="pa-4 time-range-guide">
    <h2 class="text-h6 mb-3">Time Range & Selection Guide</h2>

    <details open>
      <summary>1. Modes: Current Day vs Custom Range</summary>
      <ul>
        <li><strong>Current Day</strong>: Full selected calendar day (00:00–23:59:59).</li>
        <li><strong>Custom Range</strong>: One or more user–defined date spans.</li>
        <li>Toggle using the Current Day / Custom Range radio buttons.</li>
      </ul>
    </details>

    <details>
      <summary>2. Creating a Region Selection</summary>
      <ol>
        <li>Click the Select Region button.</li>
        <li>Drag on the map to draw a rectangle.</li>
        <li>The new selection stores the current Effective Time Range.</li>
      </ol>
    </details>

    <details>
      <summary>3. Effective Time Range</summary>
      <p>The Effective Time Range chip shows what will be applied to:</p>
      <ul>
        <li>Any brand‑new region you draw.</li>
        <li>The currently selected region <strong>only if it has no samples yet</strong>.</li>
      </ul>
    </details>

    <details>
      <summary>4. Auto‑Update Rules</summary>
      <p><strong>Auto‑updates</strong> a selection’s stored time range when ALL are true:</p>
      <ul>
        <li>It is the active (currently selected) selection.</li>
        <li>It has no samples fetched yet.</li>
        <li>You change the Effective Time Range.</li>
      </ul>
      <p><strong>Will NOT update</strong> if samples exist, it isn’t selected, or it’s a comparison copy.</p>
    </details>

    <details>
      <summary>5. Adding Another Time Series</summary>
      <p>Use “+ New Time Series for Current Selection” to copy the region with the current Effective Time Range (keeps prior data unchanged).</p>
    </details>

    <details>
      <summary>6. Fetching Data & Locking</summary>
      <ul>
        <li>“Get NO₂ Samples” downloads rectangle data.</li>
        <li>“Get Center Point NO₂ Sample” creates a center‑point copy.</li>
        <li>After data fetch, that selection’s time range is locked (no auto updates).</li>
      </ul>
    </details>

    <details>
      <summary>7. Editing Geometry</summary>
      <ul>
        <li>Editable only while no samples are fetched.</li>
        <li>Reshaping keeps its (unfetched) time range.</li>
        <li>Need a new period? Create a copy instead.</li>
      </ul>
    </details>

    <details>
      <summary>8. Multiple Custom Ranges</summary>
      <ul>
        <li>Stored as an array of ranges.</li>
        <li>Display shows overall span plus count (e.g. “Jan 2 – Jan 5 (3 ranges)”).</li>
        <li>Fetch merges data across all ranges.</li>
      </ul>
    </details>

    <details>
      <summary>9. Quick Legend</summary>
      <ul>
        <li><strong>Effective Time Range</strong>: Applied to new or unfetched current selection.</li>
        <li><strong>Selection Time Range</strong>: Frozen once samples are fetched.</li>
        <li><strong>Copy</strong>: Safe way to compare different periods.</li>
      </ul>
    </details>

    <details>
      <summary>10. Tips</summary>
      <ul>
        <li>Use “Latest” to jump to newest day.</li>
        <li>Copy to compare new periods—don’t overwrite.</li>
        <li>Subtitle under a selection shows its stored time range.</li>
      </ul>
    </details>

    <v-divider class="my-4" />
    <div class="text-caption">
      Effective range changes never modify selections that already have data.
    </div>
  </v-card>
</template>

<script setup lang="ts">
// Generated by Copilot
// No props currently; make reactive later if needed.
</script>

<style scoped>
.time-range-guide details {
  margin-bottom: 0.65rem;
  border: 1px solid #3a4a5a;
  border-radius: 6px;
  padding: 0.55rem 0.85rem;
  background: rgba(255,255,255,0.03);
}

.time-range-guide details[open] {
  background: rgba(255,255,255,0.07);
}

.time-range-guide summary {
  cursor: pointer;
  font-weight: 600;
  list-style: none;
  outline: none;
}

.time-range-guide summary::-webkit-details-marker {
  display: none;
}

.time-range-guide summary:focus-visible {
  outline: 2px solid var(--accent-color, #068ede);
  border-radius: 4px;
}

.time-range-guide ul,
.time-range-guide ol {
  margin: 0.4rem 0 0.25rem 1.1rem;
  padding: 0;
}

.time-range-guide li {
  margin-bottom: 0.25rem;
}

.time-range-guide p {
  margin: 0.4rem 0 0.4rem;
}
</style>