/**
 * Maolibre has a geojson layer. We need to be able to update it dynamically
 * This is basically meant to be a pretty thin wrapper that just helps make the data in a geojson layer reactive.
 * However we did do a few other things
 * 
 * This composable can then be used either directly, or more likely
 * wrapped in a more specific composable
 * 
 * This should really just be a thin wrapper around 
 */

import { watch, shallowRef, toRef} from "vue";
import type { Ref, MaybeRef} from "vue";
import M from 'maplibre-gl';
import type { GeoJSONSource, GeoJSONSourceSpecification, LayerSpecification } from "maplibre-gl";


// https://tkdodo.eu/blog/omit-for-discriminated-unions-in-type-script 
// Create an Omit that distributes over the unions eg X | Y | ... that make up LayerSpecification
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;
type LayerSpecOptionalId = DistributiveOmit<LayerSpecification, "id" | "source"> & { id?: string };
type LayerSpecNoSource = DistributiveOmit<LayerSpecification, "source">;
// type LayerSpec = Omit<LayerSpecification, "id" | "source"> & { id?: string }; // the id here is generally ignored in the functions it's called with
type GeoJsonLayerOptions = LayerSpecOptionalId | LayerSpecNoSource[];

interface UseGeoJsonSourceOptions {
  layerOptions: LayerSpecOptionalId,
  sourceSpec?: Omit<GeoJSONSourceSpecification, "data" | "type">, // default is empty
  sourceId?: string, // explicit source id. If omitted, autogenerated as `${name}-source`
  deepWatch?: boolean, // default false.
}

const emptyFeatureCollection: GeoJSON.FeatureCollection = {
  type: 'FeatureCollection',
  features: []
};
  
function _useGeoJsonSource(
  name: string, // source name will be `${name}-source`, will also be used for initial layer name if not provided in layerOptions
  _data: MaybeRef<GeoJSON.GeoJSON | null>,
  options: UseGeoJsonSourceOptions
) {
  
  // destructure the options and apply defaults
  const { layerOptions, sourceSpec = {}, deepWatch = false } = options;
  
  const data = deepWatch ? toRef(_data) : shallowRef(_data); // we will usually use the shallow branch
  
  // validate minimal source spec and layer options
  if (layerOptions.type === undefined) {
    throw new Error("layerOptions must have a type property that is one of the valid maplibre layer types (eg 'fill', 'line', 'circle', 'symbol', 'heatmap')");
  }
  
  // just want about this, it's not required
  if (sourceSpec.attribution === undefined) {
    console.warn("It is recommended to provide an attribution in the sourceSpec for proper attribution display on the map");
  }
  
  
  const map = shallowRef<M.Map | null>(null);
  
  const sourceId = options.sourceId ?? `${name}-source`; // if sourceId is not provided, generate it from the name
  
  const _defaultLayerId = layerOptions.id ?? `${name}-layer`; // if layer id is not provided, generate it from the name. this is just a default for the first layer, additional layers should have their own ids provided in the options.
  // keep track of layers we have added
  const layerDefinitions: Ref<Map<string, LayerSpecOptionalId | LayerSpecNoSource>> = shallowRef(new Map([[_defaultLayerId, layerOptions]])); 
  

  // 1. Add a GeoJSON source to the map
  function _addSource(map_: M.Map) {
    if (map_.getSource(sourceId)) {
      console.warn(`Source ${sourceId} already exists on map, skipping addSource`);
      return;
    }
    const _data = data.value || emptyFeatureCollection;
    map_.addSource(
      sourceId,
      {
        ...sourceSpec,
        type: 'geojson',
        data: _data,
      } as GeoJSONSourceSpecification
    );
  }
  
  /**
  * add layers, not already present, to the map
  */
  function _addLayer(map_: M.Map, layerOptions: LayerSpecNoSource) {
    if (!map_.getSource(sourceId)) {
      throw new Error(`Source ${sourceId} not found on map. Please add source before adding layer.`);
    }
    
    if (map_.getLayer(layerOptions.id)) return; // well, don't do it again
    console.log(`Adding layer ${layerOptions.id} to map with source ${sourceId}`);
    map_.addLayer({
      ...layerOptions, // has the id in it
      source: sourceId,
    } as LayerSpecification);
  }
  

  function _addAllLayers(map_: M.Map | null) {
    if (!map_) return;
    layerDefinitions.value.forEach((options, id) => {
      _addLayer(map_, {...options, id: id}); // the id from the map key will always match the id in the options if it exists, so always use it.
    });
  }
  
  /**
   * add a layer for the source to the map
   */
  function addLayer(layerOptions: LayerSpecNoSource) {
    if (layerDefinitions.value.has(layerOptions.id) || map.value?.getLayer(layerOptions.id)) { 
      console.warn(`Layer ${layerOptions.id} already exists, skipping`);
      return;
    }
    // store the user's intent
    layerDefinitions.value.set(layerOptions.id, layerOptions); 


    if (!map.value || !map.value.getSource(sourceId)) {
      if (map.value) {
        console.warn("The source is not ready (perhaps it was removed? The layer will be added if addToMap is run again");
        return;
      }
    }
    if (map.value) {
      _addLayer(map.value, layerOptions); 
    }
  }
    
  // this only run if the map is ready. when finished we can add layers and update data
  function _doAdd(map_: M.Map) {
    _addSource(map_);
    _addAllLayers(map_);
  }
  
  function addToMap(map_: M.Map) {
    if (!map_) { // you shouldn't actually be able to do this with TS, but just in case
      console.error(`Ran addToMap with a null or undefined map for ${name}`);
      return;
    }
    
    // if not set internally, set it. 
    if (!map.value) {
      map.value = map_; // set the map ref
    } else if (map.value !== map_) {
      console.warn("Map already set in useGeoJsonLayer, ignoring new map. If you intended to add this to a new map, please create a new instance of useGeoJsonLayer");
    }
    

    _doAdd(map.value);
  }
  
  
  function _removeAllLayersFromMap() {
    layerDefinitions.value.forEach((_, id) => {
      if (map.value?.getLayer(id)) {
        map.value.removeLayer(id);
      }
    });
  }
  
  function removeLayer(layerId?: string) {
    
    if (layerId === undefined) {
      _removeAllLayersFromMap();
      return;
    }
    
    if (layerDefinitions.value.has(layerId)) {
      if (map.value?.getLayer(layerId)) {
        map.value.removeLayer(layerId);
      }
    } else {
      console.warn(`Layer ${layerId} not found in layer definitions, cannot remove from here`);
    }
  }
  
  function _removeSource() {
    if (map.value?.getSource(sourceId)) {
      _removeAllLayersFromMap(); // remove all layers but keep the config.
      map.value.removeSource(sourceId);
    }
  }
  
  // Don't expose this to the outside. otherwise we will have to 
  // track the data ref and watch and make sure we aren't doubling any calls.
  function _updateData(data: GeoJSON.GeoJSON) {
    const source = map.value?.getSource(sourceId) as GeoJSONSource | undefined; // it should be geojson source, but if not, try/catch for setData
    if (source) {
      try {
        source.setData(data); // this will cause a redraw of the map
      } catch (error) {
        console.error(`Error setting data for source ${sourceId}:`, error);
      }
    } else {
      console.warn(`Attempting to update source data before source ${name} created. This is usually fine, as when it is created it will use the most recent data, but this ordering is something to check if there are loading issues`);
    }
  }
  
  function cleanup() {
    _removeSource();
    map.value = null;
  }
  
  function setData(newData: GeoJSON.GeoJSON | null) {
    // null is the same as clear data
    data.value = newData;
  }
  
  function clearData() {
    data.value = null; // this will trigger the watch to set it to empty feature collection
  }

  watch(data, (newData) => {    
    // null is treated as "clear"
    _updateData(newData ?? emptyFeatureCollection);
  }, { deep: deepWatch }); // use deep true in case we want to change things inside it. in general this can make it slower
  
  return {
    addToMap,
    addLayer, // add a new layer with the same source but different styling. will warn if layer already exists
    removeLayer,
    cleanup,
    data,
    layerDefinitions,
    setData,
    clearData
  };
}

interface UseGeoJsonLayerOptions {
  layerOptions: GeoJsonLayerOptions; // if it's an array, we will add all of them to the map. if it's not, we will add it as a single layer with the default id of `${name}-layer`
  sourceSpec?: Omit<GeoJSONSourceSpecification, "data" | "type">; // default is empty
  sourceId: string; // explicit source id. If omitted, autogenerated as `${name}-source`
  deepWatch?: boolean; // default false.
}
/**
 * A user using this is forced to give a source id
 * A user is encouraged to pass an id in the layer options, but
 * if not provided the first layer will get an id of `${name}-layer`, 
 * if more than one layer is passed, they MUST have an id in the layer. (enforced by TS & thrown error)
 */
export function useGeoJsonLayer(
  name: string,
  data: MaybeRef<GeoJSON.GeoJSON | null>,
  options: UseGeoJsonLayerOptions
) {

  const firstLayerOptions = Array.isArray(options.layerOptions) ? options.layerOptions[0] : options.layerOptions;
  const restOfTheLayers = Array.isArray(options.layerOptions) ? options.layerOptions.slice(1) : [];
  const source = _useGeoJsonSource(
    name, 
    data, 
    { 
      layerOptions: firstLayerOptions, 
      sourceSpec: options.sourceSpec, 
      deepWatch: options.deepWatch, 
      sourceId: options.sourceId 
    }); // we will use the first layer options as the default for the source, but we will add all layers in the options to the map. this is a bit of a hack but it allows us to keep the source and layer logic together in one composable. we just have to make sure to add all layers in the options to the map when we add the source.
  
  restOfTheLayers.forEach((options) => {
    if (!options.id) {
      throw new Error("When passing multiple layers in the options, each layer must have an id");
    }
    source.addLayer(options);
  }); //


  
  /**
   * Minimal value for layerOptions is {type: 'fill' | 'line' | 'circle' | 'symbol' | 'heatmap'}
   * layerId argument will override the id in the layer options if provided
   */
  function addLayer(layerId: string, layerOptions: LayerSpecOptionalId) {
    source.addLayer({...layerOptions, id: layerId}); // the source will handle the logic of adding the layer and tracking it in the layer definitions
  }

  return {
    ...source,
    addLayer: addLayer, // use the local wrapper which lets the user specify the id
    
  };
}